-   name: Separate the hosts via comma delimiter to allow multiple host deployments
    set_fact:
        fixed_nodes: "{{ nodes[retry_count|int].host }}"
        retry_count: "{{ retry_count | int + 1 }}"
    when: maintenance_action|d('')|trim == "create_bynode" and valid_play|d(false)|bool == true

-   name: Debugging execution for maintenance by node...
    debug: >-
         msg='s9s maintenance --create --nodes="{{ fixed_nodes }}" --start="{{ maintenance_start_in_datetime_format }}" --end="{{ maintenance_end_in_datetime_format }}" --reason="{{ maintenance_reason }}"'         
    when: maintenance_action|d('')|trim == "create_bynode" and valid_play|d(false)|bool == true

-   name: Execute s9s CLI to set maintenance window on a per-node basis
    command: >-
        s9s maintenance --create --nodes="{{ fixed_nodes }}" --start="{{ maintenance_start_in_datetime_format }}" --end="{{ maintenance_end_in_datetime_format }}" --reason="{{ maintenance_reason }}"
    when: maintenance_action|d('')|trim == "create_bynode" and valid_play|d(false)|bool == true

-   include_tasks: helpers/multi-node-schedule-bynode-maintenance.yml
    when: retry_count | int < nodes|length