-   name: Remove cluster
    hosts: 127.0.0.1
    connection: local
    vars:
        os_user: "root"
        os_key_file: "/root/.ssh/id_rsa"
        cluster_name: "mycluster"
        cluster_type: "galera"
        begin_date_time: "haproxy"
        nodes: "192.168.10.181"
        reason: "The reason for the maintenance"

    tasks:

    -   name: Check if cluster exists
        command:
            cmd: s9s cluster --list --long
        register: cluster_list

    -   name: Find clusters of a correct type
        set_fact:
            lines: "{{ lines|default([]) +  [item] }}"
        when: item|trim is search(cluster_type)
        with_items:
        -   "{{ cluster_list.stdout_lines }}"

    -   name: Find the cluster ID
        set_fact:
            cluster_id: "{{ item.split()[0] }}"
        when: lines is defined and item|trim is search(cluster_name)
        with_items:
        -   "{{ lines }}"

    -   name: Check the list of nodes in the cluster
        command:
            cmd: "s9s nodes --list --long --cluster-id={{ cluster_id }}"
        when: cluster_id is defined
        register: node_list

    -   name: Check if the loadbalancer has already been deployed on the node
        set_fact:
            loadbalancer: 1
        when: item.split()[5] is defined and item.split()[5] == proxy_port and item.split()[4] == proxy_host
        with_items:
        -   "{{ node_list.stdout_lines }}"

    -   debug:
            msg='s9s cluster --add-node --cluster-id={{ cluster_id }} --nodes="haproxy://{{ proxy_host }}" --os-user={{ os_user }} --os-key-file={{ os_key_file }}'
        when: loadbalancer is undefined

    -   name: Execute s9s CLI to add loadbalancer
        command:
            cmd: 's9s cluster --add-node --cluster-id={{ cluster_id }} --nodes="haproxy://{{ proxy_host }}" --os-user={{ os_user }} --os-key-file={{ os_key_file }}'
        when: loadbalancer is undefined


